# Generated by Django 3.2.4 on 2023-09-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_message_original_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Message'), ('comment', 'Comment'), ('vote', 'Vote')], max_length=20),
        ),
    ]
