# Generated by Django 3.2.4 on 2023-10-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_message_parent_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocking_users', to='users.Profile'),
        ),
    ]
