# Generated by Django 3.2.4 on 2023-10-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20231028_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='participants',
            field=models.ManyToManyField(through='users.ThreadParticipants', to='users.Profile'),
        ),
    ]
