# Generated by Django 3.2.4 on 2023-11-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_messg_viewers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messg',
            old_name='viewers',
            new_name='viewed_by',
        ),
    ]
