# Generated by Django 3.2.4 on 2023-11-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20231104_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='messg',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
