# Generated by Django 3.2.4 on 2023-11-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20231105_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='messg',
            name='viewed_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
