# Generated by Django 3.2.4 on 2023-11-06 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_auto_20231030_2103'),
        ('users', '0048_remove_notif_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_notifications', to='projects.com'),
        ),
        migrations.AddField(
            model_name='notif',
            name='notification_type',
            field=models.CharField(choices=[('FOLLOWER', 'Follower'), ('COMMENT', 'Comment')], default='FOLLOWER', max_length=10),
        ),
    ]
