# Generated by Django 3.2.4 on 2024-02-11 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_auto_20240211_1254'),
    ]

    operations = [
    ]
