# Generated by Django 3.2.4 on 2024-02-15 13:15

import devsearch.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_auto_20240211_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/user-default.png', null=True, storage=devsearch.storage_backends.B2MediaStorage(), upload_to='profiles/'),
        ),
    ]
