# Generated by Django 3.2.4 on 2024-02-22 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msg',
            name='parent_msg',
        ),
        migrations.RemoveField(
            model_name='msg',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='msg',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='msg',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='participants',
        ),
        migrations.AlterUniqueTogether(
            name='threadparticipants',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='threadparticipants',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='threadparticipants',
            name='thread',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Msg',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
        migrations.DeleteModel(
            name='ThreadParticipants',
        ),
    ]
