# Generated by Django 3.2.4 on 2024-02-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_auto_20240222_1902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
