# Generated by Django 3.2.4 on 2024-02-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notif',
            name='message',
        ),
    ]
