# Generated by Django 3.2.4 on 2024-02-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_remove_notif_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thrd',
            name='participants',
        ),
        migrations.DeleteModel(
            name='Messg',
        ),
        migrations.DeleteModel(
            name='Thrd',
        ),
    ]
