# Generated by Django 3.2.4 on 2024-02-22 12:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_auto_20240222_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participants', models.ManyToManyField(related_name='discussion_threads', to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='CommMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.BooleanField(default=False)),
                ('viewed_timestamp', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='users.commmessage')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_comm_messages', to='users.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_comm_messages', to='users.profile')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comm_messages', to='users.discussionthread')),
                ('viewed_by', models.ManyToManyField(blank=True, related_name='viewed_comm_messages', to='users.Profile')),
            ],
        ),
    ]
