# Generated by Django 3.2.4 on 2024-02-22 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_commmessage_discussionthread'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_notifications', to='users.commmessage'),
        ),
    ]
