# Generated by Django 3.2.4 on 2023-07-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_review_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='food_link',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='restaurant_name',
            new_name='deal_link',
        ),
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
