# Generated by Django 3.2.4 on 2023-10-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
