# Generated by Django 3.2.4 on 2024-02-15 13:15

import devsearch.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_auto_20231117_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(storage=devsearch.storage_backends.B2MediaStorage(), upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, storage=devsearch.storage_backends.B2MediaStorage(), upload_to=''),
        ),
    ]
