# Generated by Django 3.2.4 on 2023-07-27 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_message_original_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='original_message',
        ),
    ]
