# Generated by Django 3.2.4 on 2023-10-29 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_messg_thrd'),
    ]

    operations = [
        migrations.AddField(
            model_name='messg',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='users.messg'),
        ),
    ]
