# Generated by Django 3.2.4 on 2023-10-29 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_messg_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messg',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='messg',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends_sent_messages', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='thrd',
            name='participants',
            field=models.ManyToManyField(to='users.Profile'),
        ),
    ]
