# Generated by Django 3.2.4 on 2023-10-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_messagereadstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageReadStatus',
        ),
    ]
