# Generated by Django 3.2.4 on 2023-11-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_profile_followed_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='messg',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
