# Generated by Django 3.2.4 on 2023-11-04 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0037_messg_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='messg',
            name='last_viewed_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messg',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='viewed_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
