# Generated by Django 3.2.4 on 2023-11-04 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20231105_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messg',
            name='last_viewed_timestamp',
        ),
        migrations.RemoveField(
            model_name='messg',
            name='viewed_by',
        ),
    ]
