# Generated by Django 3.2.4 on 2023-11-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_messg_viewed_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='messg',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='viewed_messages', to='users.Profile'),
        ),
    ]
