# Generated by Django 3.2.4 on 2023-11-05 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0042_noti'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noti',
            options={},
        ),
        migrations.RenameField(
            model_name='noti',
            old_name='is_read',
            new_name='read',
        ),
        migrations.RenameField(
            model_name='noti',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='noti',
            name='message',
        ),
        migrations.RemoveField(
            model_name='noti',
            name='profile',
        ),
        migrations.AddField(
            model_name='noti',
            name='follower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='follower_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noti',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
