# Generated by Django 3.2.4 on 2023-11-05 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20231105_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_notifications', to='users.profile'),
        ),
    ]
