# Generated by Django 3.2.4 on 2023-11-06 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_auto_20231030_2103'),
        ('users', '0046_alter_notif_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_notifications', to='projects.com'),
        ),
    ]
