# Generated by Django 3.2.4 on 2023-11-06 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_notif_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notif',
            name='comment',
        ),
    ]
