# Generated by Django 3.2.4 on 2023-11-06 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_alter_notif_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_notifications', to='users.messg'),
        ),
        migrations.AlterField(
            model_name='notif',
            name='notification_type',
            field=models.CharField(choices=[('FOLLOWER', 'Follower'), ('COMMENT', 'Comment'), ('MESSAGE', 'Message')], default='FOLLOWER', max_length=10),
        ),
    ]
