# Generated by Django 3.2.4 on 2023-11-06 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20231106_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif',
            name='voting_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_notifications', to='users.profile'),
        ),
    ]
