# Generated by Django 3.2.4 on 2023-11-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_auto_20231107_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_new_followers',
            field=models.BooleanField(default=True),
        ),
    ]
