# Generated by Django 3.2.4 on 2023-11-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_profile_notify_new_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
