# Generated by Django 3.2.4 on 2023-11-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_profile_notify_new_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_new_comment_on_project',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_new_replied_comment',
            field=models.BooleanField(default=True),
        ),
    ]
