# Generated by Django 3.2.4 on 2023-11-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_auto_20231107_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_new_upvote_on_project',
            field=models.BooleanField(default=True),
        ),
    ]
