# Generated by Django 3.2.4 on 2024-02-11 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_auto_20240211_1258'),
    ]

    operations = [

    ]