# Generated by Django 3.2.4 on 2023-07-27 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_delete_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='original_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='users.message'),
        ),
    ]
