# Generated by Django 3.2.4 on 2023-10-27 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20231024_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='parent_msg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='users.msg'),
        ),
    ]
