# Generated by Django 3.2.4 on 2023-10-29 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20231029_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messg',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.thrd'),
        ),
    ]
