# Generated by Django 3.2.4 on 2023-10-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_thrd_read_by_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thrd',
            name='read_by_users',
        ),
    ]
