# Generated by Django 3.2.4 on 2023-10-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_auto_20231030_2103'),
        ('users', '0031_remove_thrd_read_by_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followed_tags',
            field=models.ManyToManyField(blank=True, related_name='followers', to='projects.Tag'),
        ),
    ]
