# Generated by Django 3.2.4 on 2023-11-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_messg_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='messg',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewed_messages', to='users.Profile'),
        ),
    ]
