# Generated by Django 3.2.4 on YYYY-MM-DD HH:MM
from django.db import migrations

def delete_null_users_notis(apps, schema_editor):
    Noti = apps.get_model('users', 'Noti')  # Change 'users' to your actual app name where Noti model is defined
    Noti.objects.filter(user__isnull=True).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20231105_2006'),  # This should be your last applied migration
    ]

    operations = [
        migrations.RunPython(delete_null_users_notis),
    ]
