# Generated by Django 3.2.4 on 2023-11-06 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_auto_20231030_2103'),
        ('users', '0051_auto_20231106_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_notifications', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='notif',
            name='notification_type',
            field=models.CharField(choices=[('FOLLOWER', 'Follower'), ('COMMENT', 'Comment'), ('MESSAGE', 'Message'), ('VOTE', 'Vote')], default='FOLLOWER', max_length=10),
        ),
    ]
