# Generated by Django 3.2.4 on 2023-11-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_notif_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_new_messages',
            field=models.BooleanField(default=True),
        ),
    ]
