# Generated by Django 3.2.4 on 2024-02-11 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_profile_notify_new_upvote_on_project'),
    ]

    operations = [
    ]
