# Generated by Django 3.2.4 on 2023-07-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20230724_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
