# Generated by Django 3.2.4 on 2023-10-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_com_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='com',
            name='likes',
        ),
    ]
