# Generated by Django 3.2.4 on 2023-10-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sumvote',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
