# Generated by Django 3.2.4 on 2023-10-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_auto_20231030_0041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voting',
        ),
    ]
