# Generated by Django 3.2.4 on 2023-10-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_auto_20231030_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
