# Generated by Django 3.2.4 on 2023-10-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_messg_thread'),
        ('projects', '0042_auto_20231030_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='com',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to='users.Profile'),
        ),
    ]
