# Generated by Django 3.2.4 on 2023-10-30 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_alter_like_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
